### ISSUE TITLE
Tree representation of Git history

### ISSUE THREAD

**Issue by kbariotis** [buunguyen/octotree#418] opened 2017-07-16 14:15 UTC
Would it be possible to have a tree representation of the repository's Git history? Much like Sourcetree?

**Comment by crashbell** [comment] 2017-07-23 10:22
Regarding the description of Octotree: 

> Browser extension (Chrome, Firefox, Opera and Safari) to show a code tree on GitHub. Awesome for exploring project source without having to pull every single repository to your machine.

A git history tree looks out of scope since Octotree was designed to help us view project structure quickly.

**Comment by kbariotis** [comment] 2017-07-27 20:53
I see @crashbell! Indeed, I just thought I would be a good feature alongside the project structure.

**Closed** 2017-08-10 18:53 UTC
