### ISSUE TITLE
Latest Version have some bugs...

### ISSUE THREAD

**Issue by mikhoul** [buunguyen/octotree#249] opened 2016-02-02 03:38 UTC
<ins>**Very Slow**</ins> to load and some characters are not decoded...

http://i.imgur.com/GqkCREF.png

**Comment by Joshua-F** [comment] 2016-02-02 04:00
Dupe of #248? If so it was fixed in 2.0.4.

**Comment by buunguyen** [comment] 2016-02-02 04:09
If Chrome, then it's a duplicate. Firefox/Opera/Safari don't have fix yet.

**Closed by buunguyen** 2016-02-02 04:09 UTC

**Comment by mikhoul** [comment] 2016-02-02 04:50
On Firefox, Do you have a version compiled (XPI file) ?

**Comment by buunguyen** [comment] 2016-02-02 04:52
Sorry, no solution for Firefox yet. https://github.com/buunguyen/octotree/issues/250
