### ISSUE TITLE
Filter tree based on PR

### ISSUE THREAD

**Issue by jeremyalan** [buunguyen/octotree#313] opened 2016-07-27 02:56 UTC
When viewing a Pull Request, it would be AWESOME to filter the tree-view to include only the files relevant for the PR.  When clicking on a particular file in the tree, the screen would "jump" to that file in the PR.

This would make navigating large PRs, and ignoring certain files (like static assets, and compiled output), much easier!

Btw, I love this extension!! Thanks, and keep up the good work!

**Comment by stefanosaittamrf** [comment] 2016-08-03 09:25
This is exactly the need that we have as well, i guess i'm about to propose a PR for this. But what you think is better on terms of UI, when in the PR view open extend the directory with the modified files on it highlighted, or see a new filesystem tree with just the files? The second one to me doesn't add nothing

**Comment by jeremyalan** [comment] 2016-08-03 17:21
I would like to hear some feedback from the maintainer(s) of this project, but since I posted the request, here's my $.02.  This is just my opinion, so I encourage everyone to keep the discussion open!

I see pros and cons to each approach... I personally like the idea of a separate tree, but I see how that "forks" the user experience to behave quite a bit differently, depending on when I'm in PR mode or not.

In favor of showing the full tree:
* If I'm reviewing a change, and I want to quickly view a separate file, perhaps a class declaration not part of the PR, to see what properties it has, or whether or not a particular field is required.

In favor of showing only the PR files:
* In a monolithic repo, the file changes could be scattered, and scrolling through the entire tree to find the files that have changed could be rather cumbersome.  It makes it difficult to see at-a-glance the scope of changes that were made.

Given the subjective nature of this decision, perhaps this is something that can be controlled via user settings.

Option 1: Put an option in the Settings screen
```
When viewing a Pull Request
(*) Only show files changed the Pull Request
( ) Show all files, with changes highlighted
( ) Do not show changes
```

Option 2: Put a clickable link in the tree view, e.g. "Show all files"

I don't know how much effort is involved with either of these choices, so please take that into consideration, I'm just giving my opinion from the perspective of someone who loves using this plugin!

**Comment by buunguyen** [comment] 2016-08-04 20:37
I suppose the approach providing an option to users makes sense. Can we simplify it to a single toggle instead of 3 different options? For example: "Show only changed files in a pull request".

**Comment by stefanosaittamrf** [comment] 2016-08-29 08:27
I'm actually working on this, i will provide you a PR as soon as possible. @buunguyen

**Comment by stefanosaittamrf** [comment] 2016-09-05 14:33
The implementation is done for github, i'm about to implement it for gitlab as well, but i don't have a way for testing it, so maybe you can help me with this.

**Comment by buunguyen** [comment] 2016-09-06 19:41
@stefanosaittamrf you can create an account on GitLab. It's free. Let me know how I can help.

**Comment by stefanosaittamrf** [comment] 2016-09-07 00:45
@buunguyen 👍 i will do that. I will finalize the tests and do the pull request without gitlab, because i guess you will change a bit the way i implemented it. Once done the refactoring i will implement the gitlab one. 👓

**Comment by mcuadros** [comment] 2016-09-18 16:22
I was working, on a kind of similar feature for my usage, works with commits and PRs, when you are in a PR the tree is the tree referenced by the PR and the tree also includes number of additions and deletions and the renamed files

![screenshot_2016-09-18_18-18-12](https://cloud.githubusercontent.com/assets/1573114/18617292/61c959b2-7dcc-11e6-99e4-1a383180543d.png)

I am making a PR in a few days, after test it. Only works with GitHub.
https://github.com/mcuadros/octotree/commits/master

I must to say that I am not used to code in frontend projects, so my code maybe is not very good to be merged.

**Comment by stefanosaittamrf** [comment] 2016-09-19 20:47
@mcuadros Very Nice! I guess that the expected behaviour here was to filter the tree showing just the PR involved files. I complete my implementation just for github as well but i would like to add the addition/removal to mine as well, maybe we should merge this 2 into a single one. As a proposal i'm also try to add the anchor to go directly on the pr file view instead of go on the filesystem one. Let me know what you think about it.

cc @buunguyen

**Comment by mcuadros** [comment] 2016-09-20 12:47
@stefanosaittamrf the jump, directly tot he file on the diff is also implemented on mine. (https://github.com/mcuadros/octotree/blob/master/src/adapters/github.js#L208-L214) 

The idea of having only the changed files, should be optional, at least for me lack of interested for example, but I understand that for other people could be interesting. 

If you want to merge both forks, for me is ok, I can help on it, but not much. :( but will be great having the feature available in octotree.

**Comment by RonakMehta25** [comment] 2016-10-29 19:59
hello @stefanosaittamrf  @buunguyen @mcuadros I really liked this project and I want to contribute to this project . Can you help me on which issue i can help . Thankyou .

**Comment by jeremyalan** [comment] 2016-10-31 16:19
I really like the additions glyph next to each of the file!! That looks really slick, and I could see that definitely being helpful.  What's the status on getting this merged, I can't wait to start using it!! :-D

**Comment by stefanosaittamrf** [comment] 2016-11-01 19:09
Sorry for the long wait, i have been very busy at work, i guess that i'll propose my PR maximum in the next 2week. Sorry for the wait. 🙏

**Comment by lukasniemeier-zalando** [comment] 2016-12-04 11:40
@stefanosaittamrf :+1: on the proposals in here, looking forward to this - if you need help with testing please ping

**Comment by jchannon** [comment] 2016-12-08 12:22
Can't wait either!

**Comment by jchannon** [comment] 2017-01-17 15:09
Where we at with this?

**Comment by jamby** [comment] 2017-02-21 15:17
Agree, where is the PR for this? I'm currently getting an "Error: Private Repository" on the Octotree plugin whenever viewing PRs and would love for it to be something more informative.

**Comment by buunguyen** [comment] 2017-03-03 21:47
@jamby the private repo in PRs should have been fixed in the latest update.

**Comment by sromocki** [comment] 2017-04-05 15:10
@stefanosaittamrf Did you have a PR you were going to submit for this?   Is there a fork/branch I can look at to piece together what's left?  Would be a shame to start from scratch again.

**Comment by bigredwill** [comment] 2017-08-23 00:26
I've submitted a PR addressing this issue: https://github.com/buunguyen/octotree/pull/428

**Comment by buunguyen** [comment] 2017-08-29 22:36
I've just released a new version of Octotree to the stores. Thanks everyone for contributing ideas, code and especially @bigredwill for driving this to the finish line!

**Closed by buunguyen** 2017-08-29 22:36 UTC
Labels: enhancement, help wanted
