### ISSUE TITLE
Support new github design.

### ISSUE THREAD

**Issue by skyhacker2** [buunguyen/octotree#210] opened 2015-11-17 13:58 UTC

**Comment by buunguyen** [comment] 2015-11-17 21:35
What new design?

**Comment by joedf** [comment] 2015-11-17 22:47
I think he means the new upcoming GitHub Repository design.

See here: https://github.com/blog/2085-a-new-look-for-repositories

Example Screenshot: 
![2015-11-17_174230](https://cloud.githubusercontent.com/assets/3848219/11227310/3cfc2598-8d53-11e5-93e9-3122cda5dc26.png)

**Comment by buunguyen** [comment] 2015-11-17 22:51
Thanks, I wasn't aware of that. How to opt-in the new design?

**Comment by joedf** [comment] 2015-11-17 23:07
I went on one of my own repositories and just saw a message (today, actually) to try it before it is fully out.
I'm not sure...

**Comment by buunguyen** [comment] 2015-11-19 22:51
@Ephemera can you help with this? Probably conditionally apply the appropriate logic depending on whether old or new layout is detected. Thanks in advance!

**Comment by joedf** [comment] 2015-11-20 02:48
I have not looked at Octotree's code. I'm not sure, but I think the class `reponav` is used uniquely in the new page style. Can you confirm this? If so, it could be used for detection of the "new" design.

Either way, I've discovered that octotree adds a `margin-left` to the `<html>`.
For me, it is currently adding a margin of 264px: `margin-left: 264px;`
I have tried modifying this offset and it seems to me, it just needs a little shift of 10 pixels.
So, for the "new" style it should be using this instead `margin-left: 254px;`. and it then, looks fine.
This is of course depending whether the original margin value varies or not, but I am certain of the 10px offset.

**Comment by Ephemera** [comment] 2015-11-20 04:25
@buunguyen 
Okay, I'll try this weekend :grinning:

**Comment by buunguyen** [comment] 2015-11-24 19:09
@Ephemera any update on this?

**Comment by crashbell** [comment] 2015-11-25 00:12
I have created new PR  to fix that issue.

**Comment by buunguyen** [comment] 2015-11-25 00:29
@crashbell thanks, that should fix #213. However, the behavior of the sidebar isn't correct in the new layout: it pushes the GitHub container away even though the sidebar hasn't touch the container. In the old design, resize the sidebar won't push the container until the sidebar starts to touch within 10px. The issue is in `updateLayout()` (https://github.com/buunguyen/octotree/blob/v2/src%2Fadapters%2Fgithub.js#L44). The containers are likely changed in the new design, thus need to handle differently for old and new.

**Comment by crashbell** [comment] 2015-11-25 00:34
@buunguyen ah, I intended to mention #213. Sorry for this wrong post. How about `if-else` in this case for old and new design?

**Comment by crashbell** [comment] 2015-11-25 00:45
I found out that the length of `containers` has changed: https://github.com/buunguyen/octotree/blob/v2/src%2Fadapters%2Fgithub.js#L48. Now it's 5 so it will fallback to changing `html` margin. It will be fixed soon.

**Comment by Ephemera** [comment] 2015-11-25 02:07
@buunguyen 
Sorry for late reaction.
I [fixed](https://github.com/Ephemera/octotree/compare/v2...fix-v2-bug) this issue but did not consider backward compatiblity.

**Comment by joedf** [comment] 2015-11-25 16:14
What is the current situation with this? I can make a pull request. Did anybody consider detecting the old versus new design?

**Comment by crashbell** [comment] 2015-11-25 18:53
@joedf I made a [PR](https://github.com/buunguyen/octotree/pull/214) for this issue.

**Comment by buunguyen** [comment] 2015-11-25 21:09
The fix for this is available in v2, you can test now with the prebuilt package https://github.com/buunguyen/octotree/tree/v2/dist. Will release to store in about a week.

Thanks @crashbell for helping out on this.

**Closed by buunguyen** 2015-11-25 21:09 UTC

**Comment by joedf** [comment] 2015-11-25 22:35
Ok, great! :+1:
