### ISSUE TITLE
Pull Requests from external repos fail with a 404 error

### ISSUE THREAD

**Issue by j-f1** [buunguyen/octotree#384] opened 2017-03-06 22:30 UTC
### Description
Since the branch is not present on the destination repo, it can’t be loaded.

The `title` attribute of the `.head-ref` element provides info on the correct repo to look at.

### Environment (if bug)

* Octotree version: 2.0.18
* Browser & version: Safari 10.0.3 (12602.4.8)
* OS & version: macOS 10.12.3 (16D32)
* Screenshot, if any (drag an image here)

<img width="244" alt="Screenshot" src="https://cloud.githubusercontent.com/assets/25517624/23633044/2a511f2e-0292-11e7-883f-ddb8b2891aca.png">

**Comment by buunguyen** [comment] 2017-03-11 04:23
Can you send an example? Greater is an PR! :)

**Comment by j-f1** [comment] 2017-03-11 11:45
@buunguyen Steps to reproduce:
1. Fork a repository to your own account
2. Add a new branch to it (that doesn’t exist in the parent repository)
3. Create a pull request and view it

Example: tomocchino/isfiberreadyyet#1

**Comment by buunguyen** [comment] 2017-08-10 22:46
Please check 2.2.0 (will be released shortly), if the issue is still there, let me know.

**Closed by buunguyen** 2017-08-10 22:46 UTC
